language: ruby

rvm:
  - 2.5.0

services:
  - docker

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
  - bundle install --jobs=3 --retry=3
  - rake build
  - docker build -f Dockerfile-travis -t $TRAVIS_REPO_SLUG .

script:
  # - rake proofer
  - rake build

after_success:
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker push $TRAVIS_REPO_SLUG

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
