env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - secure: "QMVa7Ja2xn919KdTn67Tv3nuiW6Zjmxyn3/AJHlAw4aII5fLXIqsLQZBk4goCecuzKDX6L3aHtTS+E5H4ZFg/CAMIsHvI1PXY5LrYiJkaxcQl6qiUGjvGRQ/nXrY5QhE7dd5tra5bQ/UGN72gcCBnWhMOoiXQhtDYZxQ8lzdzWEURwRHHBSEifr8GEj3F/n1N9JRmmjQWVOqRHZnTLIIPXhEepwp2t7ZMFr5ZGDMLBHixXsw5x2uSFlEYG5PEaP9VZnk8TvoM+c8tFJiNkoZwXvsuayb2EBwkNf/+SK8LuaMDg/kT2P23SMydmUY3bcfiggVPWK01hRdgAPejRgbsJ5VH38Gz+TnqieLtPS/SquXLeweM0vMXuTfNkHbEthgmDF/6Iis2e5dXMPo7CkXFIW7tn8iEnUPv4XWEUAcNXhuvVB35J9hYa+Gw/U/BGU/YVc6C9yFe0IbkmH67Zw00nNnipUDNM8B8ZWoMaaIDZGjQGetiS0zq0+slBYoA2VAro7zz3xu6rcTgqnwxYbd7ORp7ffNfliAQ6sDZT23PG+CNEO3GwvHpgp/+zIsp/+GYdCZITa/5iK0NAp7ry/NDQcIXWKetGwMBEq/UVVznfK7ogJelFL8DVM+8Ua/BGSmmYPUDe510pODARMFrJ0HF5yLE/jOgN8EprmoqWbe5uk="
    - secure: "KZIau6WluDTQFw47n6zuH2lwgTatU3LVUwkdJ6cPHlMp6CuDIR6Epn48Mp8V3/0EpvoZN1rrQTpqBGQPYaECg23gGFUfPOrFZbB9moV9rCK7aNRnjY3y8o6f+hSA27/u3U2XqP+chxDrTXyF09KpqmRaNSwXkXA8FJjqvLnfhSDnoiGd3gdmQHiOd4Uc4kc/d9uAtWiIGHlDj08IKUHIX/dHg8BQeLayy+XX5j1h+uFVtuxsesbwCYeV8ZbRxuUq61GTtp1guV0Q3+62DpI0RBAyLuIzLO4DpDmHtMhyWS+6+JGie/XtEzl7Bpqmpk6vmlTNH+kR2m8QM3TtcTFalhHVus/JK03Rm4BbJyMmiefl86Hwlk6kjpYbGd5jNlF1qh9Rrix5JIX4n9W2iwpufw6xpxLEe+MWzQHPmQFCJAcqqAyJ5SRJ0Qz8xNmJUwigOaX6Lb97HmMF6m9kzh4DKjegq39P/6foA1Am42GYpNMuwB64cg1RMaCoAWV/5RCqbGzISJRsMSBYSqRkHyQH14q0XYzwDPAQsNcvLOSDBV0+M12m4+ehSyTJFA0lKR9KfeEESRqYOiNGMlDcwYJVVy5/TYOsM8FJP1JN0ejJEwQi7ns//bfScfr4UoDxtRwdJb+GvfUSzaASsRCfLESsBXJuP71UTS5ybHOf+23+e2U="

os:
  - linux

language: ruby

rvm:
  - 2.7.0

services:
  - docker

install:
  - bundle install --jobs=3 --retry=3
  - rake build
  - docker build -f Dockerfile-travis -t $TRAVIS_REPO_SLUG .

script:
#  - rake proofer
  - echo "skip - do nothing"

after_success:
  - echo "$DOCKERHUB_PWD" | docker login --username "$DOCKERHUB_USR" --password-stdin
  - docker push $TRAVIS_REPO_SLUG

deploy:
  provider: pages
  skip_cleanup: true
  token:
    secure: "JrpVwXCxwHOK8Q8I9LwyeiNzGvi8SmLZ8e0Gei6SXbStyTKseGPp+6SFkUR4KD/q5901gcd8TLMpn3t10MW7I3Bcpvi+0I6zblk0Y088+5eb1g/d34ALSIezpSRwiwLlbNLsuSi5LgrYQM2S9mybwQrkz8PlKdwVwuMkL3LdtgYd9+qReH7FrO5ZL6IouA1vKqnlo9TLaix417jY4N6Z78CZrCoeetOKLcw+OxY4nJc//UXLr7oXjYI2dt6KM1Jo6mguhMO7Hv305G/F5icU7rdUK2J8AEuilpwX2rtZAYA2vDFUBNTbWCkdfIVnGJY1v0y8057jS8TT5k3KT/yepR8xEMiSNNOa817XFD19E45c/msO7+5JbOg5l6tbqcUP9sCtC9v+7yIzZRRCLmBxheVKCy2gDPZhIOzvh7JWqDE/L35xOjHI9+bOMLxjvxJT3KFvmqwRqzpISYQQh4boxZIPBBCVGHQxW5+4/dBYd661+VvK6Rbjd9o1++OnPlNHzaKIjria+OxpROsBt2gmQb51Her06bHxP8qaIObjrunHdCWIPY2JIV2QQxPzMX4Wx0Qeji6IYyoTV2KDjZ31zyW5HcuUWnk1yvGa3OJPHgTTnTrK42g6wqv8GXdab+XUiUjrDmtvYKy5KKBA1iIRagk2JlyAVASfPug6qyXguhs="
  local_dir: _site
  on:
    branch: master
